name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: adjust/pg-ext-actions/pg-setup@master
        with:
          version: 18
          install-contrib: 'true'

      - uses: actions/checkout@v6
      - run: make install
